/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun Mar 22 21:45:53 GMT 2020
 */

package nl.tudelft.oopp.group43.project.controllers;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class BikeController_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "nl.tudelft.oopp.group43.project.controllers.BikeController"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/bb/jflygsqs62q45k_4jdyk7knm0000gn/T/"); 
    java.lang.System.setProperty("user.country", "CN"); 
    java.lang.System.setProperty("user.dir", "/Users/skylove/CSE1105/repository-template/server/src/main"); 
    java.lang.System.setProperty("user.home", "/Users/skylove"); 
    java.lang.System.setProperty("user.language", "zh"); 
    java.lang.System.setProperty("user.name", "skylove"); 
    java.lang.System.setProperty("user.timezone", "Europe/Amsterdam"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(BikeController_ESTest_scaffolding.class.getClassLoader() ,
      "com.fasterxml.jackson.annotation.JsonProperty",
      "nl.tudelft.oopp.group43.project.models.Role",
      "nl.tudelft.oopp.group43.project.payload.SuccessResponse",
      "org.springframework.beans.factory.annotation.Autowired",
      "nl.tudelft.oopp.group43.project.repositories.BuildingRepository",
      "com.fasterxml.jackson.annotation.JacksonAnnotation",
      "nl.tudelft.oopp.group43.project.repositories.UserRepository",
      "org.springframework.data.repository.Repository",
      "org.springframework.data.domain.Sort",
      "org.springframework.data.domain.Pageable",
      "org.springframework.stereotype.Repository",
      "nl.tudelft.oopp.group43.project.payload.BikeReservationResponse",
      "nl.tudelft.oopp.group43.project.models.BuildingFoodProduct",
      "nl.tudelft.oopp.group43.project.models.BikeReservation",
      "com.fasterxml.jackson.annotation.JsonBackReference",
      "org.springframework.data.repository.PagingAndSortingRepository",
      "org.springframework.http.HttpHeaders",
      "com.fasterxml.jackson.annotation.JsonCreator$Mode",
      "org.springframework.data.domain.Page",
      "org.springframework.data.domain.Example",
      "nl.tudelft.oopp.group43.project.models.User",
      "org.springframework.web.bind.annotation.RestController",
      "org.springframework.data.domain.Slice",
      "org.springframework.http.HttpEntity",
      "nl.tudelft.oopp.group43.project.models.FoodOrder",
      "org.springframework.data.util.Streamable",
      "org.springframework.util.CollectionUtils",
      "nl.tudelft.oopp.group43.project.models.Building",
      "org.springframework.http.ResponseEntity$HeadersBuilder",
      "com.fasterxml.jackson.annotation.JsonManagedReference",
      "nl.tudelft.oopp.group43.project.models.Bike",
      "org.springframework.data.jpa.repository.JpaRepository",
      "nl.tudelft.oopp.group43.project.repositories.BikeReservationRepository",
      "nl.tudelft.oopp.group43.project.models.Room",
      "org.springframework.util.LinkedCaseInsensitiveMap",
      "org.springframework.stereotype.Controller",
      "org.springframework.http.ResponseEntity$BodyBuilder",
      "org.springframework.data.repository.CrudRepository",
      "org.springframework.http.ReadOnlyHttpHeaders",
      "org.springframework.util.LinkedCaseInsensitiveMap$EntrySet",
      "com.fasterxml.jackson.annotation.JsonIgnore",
      "org.springframework.stereotype.Indexed",
      "com.fasterxml.jackson.annotation.JsonProperty$Access",
      "org.springframework.util.MultiValueMap",
      "org.springframework.web.bind.annotation.ResponseBody",
      "nl.tudelft.oopp.group43.project.payload.ErrorResponse",
      "org.springframework.util.CollectionUtils$MultiValueMapAdapter",
      "org.springframework.util.LinkedCaseInsensitiveMap$1",
      "org.springframework.data.repository.query.QueryByExampleExecutor",
      "org.springframework.http.HttpStatus",
      "org.springframework.stereotype.Component",
      "nl.tudelft.oopp.group43.project.repositories.BikeRepository",
      "nl.tudelft.oopp.group43.project.models.Reservation",
      "nl.tudelft.oopp.group43.project.controllers.BikeController",
      "com.fasterxml.jackson.annotation.JsonCreator",
      "org.springframework.http.ResponseEntity",
      "org.springframework.util.LinkedMultiValueMap",
      "org.springframework.util.Assert"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("java.util.Date", false, BikeController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("nl.tudelft.oopp.group43.project.models.Bike", false, BikeController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("nl.tudelft.oopp.group43.project.models.BikeReservation", false, BikeController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("nl.tudelft.oopp.group43.project.models.Building", false, BikeController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("nl.tudelft.oopp.group43.project.models.User", false, BikeController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("nl.tudelft.oopp.group43.project.repositories.BikeRepository", false, BikeController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("nl.tudelft.oopp.group43.project.repositories.BikeReservationRepository", false, BikeController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("nl.tudelft.oopp.group43.project.repositories.BuildingRepository", false, BikeController_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("nl.tudelft.oopp.group43.project.repositories.UserRepository", false, BikeController_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(BikeController_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "nl.tudelft.oopp.group43.project.controllers.BikeController",
      "org.springframework.http.HttpStatus",
      "com.fasterxml.jackson.annotation.JsonProperty$Access",
      "nl.tudelft.oopp.group43.project.models.Bike",
      "com.fasterxml.jackson.annotation.JsonCreator$Mode",
      "nl.tudelft.oopp.group43.project.models.Building",
      "nl.tudelft.oopp.group43.project.models.BikeReservation",
      "nl.tudelft.oopp.group43.project.models.User",
      "nl.tudelft.oopp.group43.project.payload.ErrorResponse",
      "org.springframework.http.ReadOnlyHttpHeaders",
      "org.springframework.util.LinkedMultiValueMap",
      "org.springframework.util.Assert",
      "org.springframework.http.HttpHeaders",
      "org.springframework.util.LinkedCaseInsensitiveMap",
      "org.springframework.util.LinkedCaseInsensitiveMap$1",
      "org.springframework.util.CollectionUtils",
      "org.springframework.util.CollectionUtils$MultiValueMapAdapter",
      "org.springframework.http.HttpEntity",
      "org.springframework.http.ResponseEntity",
      "org.springframework.util.LinkedCaseInsensitiveMap$EntrySet",
      "nl.tudelft.oopp.group43.project.payload.BikeReservationResponse",
      "nl.tudelft.oopp.group43.project.payload.SuccessResponse"
    );
  }
}
