/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 21:48:39 GMT 2020
 */

package nl.tudelft.oopp.group43.project.controllers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import nl.tudelft.oopp.group43.project.controllers.FoodOrderController;
import nl.tudelft.oopp.group43.project.models.FoodOrder;
import nl.tudelft.oopp.group43.project.repositories.FoodOrderRepository;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FoodOrderController_ESTest extends FoodOrderController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FoodOrderController foodOrderController0 = new FoodOrderController();
      FoodOrderRepository foodOrderRepository0 = mock(FoodOrderRepository.class, new ViolatedAssumptionAnswer());
      doReturn((List) null).when(foodOrderRepository0).findAll();
      Injector.inject(foodOrderController0, (Class<?>) FoodOrderController.class, "repository", (Object) foodOrderRepository0);
      Injector.validateBean(foodOrderController0, (Class<?>) FoodOrderController.class);
      List<FoodOrder> list0 = foodOrderController0.getFoodOrder();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FoodOrderController foodOrderController0 = new FoodOrderController();
      FoodOrderRepository foodOrderRepository0 = mock(FoodOrderRepository.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(foodOrderRepository0).save(nullable(java.lang.Object.class));
      Injector.inject(foodOrderController0, (Class<?>) FoodOrderController.class, "repository", (Object) foodOrderRepository0);
      Injector.validateBean(foodOrderController0, (Class<?>) FoodOrderController.class);
      // Undeclared exception!
      try { 
        foodOrderController0.createFoodOrder((FoodOrder) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("nl.tudelft.oopp.group43.project.controllers.FoodOrderController", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FoodOrderController foodOrderController0 = new FoodOrderController();
      FoodOrderRepository foodOrderRepository0 = mock(FoodOrderRepository.class, new ViolatedAssumptionAnswer());
      doReturn("").when(foodOrderRepository0).save(nullable(java.lang.Object.class));
      Injector.inject(foodOrderController0, (Class<?>) FoodOrderController.class, "repository", (Object) foodOrderRepository0);
      Injector.validateBean(foodOrderController0, (Class<?>) FoodOrderController.class);
      FoodOrder foodOrder0 = mock(FoodOrder.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        foodOrderController0.createFoodOrder(foodOrder0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to nl.tudelft.oopp.group43.project.models.FoodOrder
         //
         verifyException("nl.tudelft.oopp.group43.project.repositories.FoodOrderRepository$MockitoMock$285281741", e);
      }
  }
}
