/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 21:49:52 GMT 2020
 */

package nl.tudelft.oopp.group43.project.payload;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class ErrorResponseTest extends ErrorResponseTestScaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        ErrorResponse errorResponse0 = new ErrorResponse((String) null, "nl.tudelft.oopp.group43.project.payload.ErrorResponse", 304);
        errorResponse0.setStatus(0);
        int int0 = errorResponse0.getStatus();
        assertEquals(0, int0);
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        ErrorResponse errorResponse0 = new ErrorResponse((String) null, "nl.tudelft.oopp.group43.project.payload.ErrorResponse", 304);
        int int0 = errorResponse0.getStatus();
        assertEquals(304, int0);
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        ErrorResponse errorResponse0 = new ErrorResponse((String) null, "nl.tudelft.oopp.group43.project.payload.ErrorResponse", 304);
        errorResponse0.setMessage((String) null);
        errorResponse0.getMessage();
        assertEquals(304, errorResponse0.getStatus());
    }

    @Test(timeout = 4000)
    public void test3() throws Throwable {
        ErrorResponse errorResponse0 = new ErrorResponse("!KM'rYr", "m\"^6hpC$pIh$|cV&B$", (-4035));
        String string0 = errorResponse0.getMessage();
        assertEquals((-4035), errorResponse0.getStatus());
        assertEquals("!KM'rYr", errorResponse0.getError());
        assertEquals("m\"^6hpC$pIh$|cV&B$", string0);
    }

    @Test(timeout = 4000)
    public void test4() throws Throwable {
        ErrorResponse errorResponse0 = new ErrorResponse((String) null, "nl.tudelft.oopp.group43.project.payload.ErrorResponse", 304);
        String string0 = errorResponse0.getError();
        assertEquals(304, errorResponse0.getStatus());
        assertNull(string0);
    }

    @Test(timeout = 4000)
    public void test5() throws Throwable {
        ErrorResponse errorResponse0 = new ErrorResponse((String) null, "nl.tudelft.oopp.group43.project.payload.ErrorResponse", 304);
        errorResponse0.setError("e,Xbxp?k|{\"&");
        errorResponse0.getError();
        assertEquals(304, errorResponse0.getStatus());
    }

    @Test(timeout = 4000)
    public void test6() throws Throwable {
        ErrorResponse errorResponse0 = new ErrorResponse("", "", (-1));
        errorResponse0.getMessage();
        assertEquals((-1), errorResponse0.getStatus());
    }

    @Test(timeout = 4000)
    public void test7() throws Throwable {
        ErrorResponse errorResponse0 = new ErrorResponse("", "", (-1));
        errorResponse0.getError();
        assertEquals((-1), errorResponse0.getStatus());
    }

    @Test(timeout = 4000)
    public void test8() throws Throwable {
        ErrorResponse errorResponse0 = new ErrorResponse("", "", (-1));
        int int0 = errorResponse0.getStatus();
        assertEquals((-1), int0);
    }
}
