/**
 * Scaffolding file used to store all the setups needed to run
 * tests automatically generated by EvoSuite
 * Sun Mar 22 21:48:49 GMT 2020
 */

package nl.tudelft.oopp.group43.project.payload;

import static org.evosuite.shaded.org.mockito.Mockito.mock;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;

@EvoSuiteClassExclude
public class ReservationResponse_ESTest_scaffolding {

    @org.junit.Rule
    public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

    private static final java.util.Properties defaultProperties = (java.util.Properties) System.getProperties().clone();

    private org.evosuite.runtime.thread.ThreadStopper threadStopper = new org.evosuite.runtime.thread.ThreadStopper(org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


    @BeforeClass
    public static void initEvoSuiteFramework() {
        org.evosuite.runtime.RuntimeSettings.className = "nl.tudelft.oopp.group43.project.payload.ReservationResponse";
        org.evosuite.runtime.GuiSupport.initialize();
        org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100;
        org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;
        org.evosuite.runtime.RuntimeSettings.mockSystemIn = true;
        org.evosuite.runtime.RuntimeSettings.sandboxMode = SandboxMode.RECOMMENDED;
        Sandbox.initializeSecurityManagerForSUT();
        org.evosuite.runtime.classhandling.JDKClassResetter.init();
        setSystemProperties();
        initializeClasses();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
        try {
            initMocksToAvoidTimeoutsInTheTests();
        } catch (ClassNotFoundException e) {
        }
    }

    @AfterClass
    public static void clearEvoSuiteFramework() {
        Sandbox.resetDefaultSecurityManager();
        System.setProperties((java.util.Properties) defaultProperties.clone());
    }

    @Before
    public void initTestCase() {
        threadStopper.storeCurrentThreads();
        threadStopper.startRecordingTime();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler();
        Sandbox.goingToExecuteSUTCode();
        setSystemProperties();
        org.evosuite.runtime.GuiSupport.setHeadless();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
        org.evosuite.runtime.agent.InstrumentingAgent.activate();
    }

    @After
    public void doneWithTestCase() {
        threadStopper.killAndJoinClientThreads();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks();
        org.evosuite.runtime.classhandling.JDKClassResetter.reset();
        resetClasses();
        Sandbox.doneWithExecutingSUTCode();
        org.evosuite.runtime.agent.InstrumentingAgent.deactivate();
        org.evosuite.runtime.GuiSupport.restoreHeadlessMode();
    }

    public static void setSystemProperties() {

        System.setProperties((java.util.Properties) defaultProperties.clone());
        System.setProperty("file.encoding", "UTF-8");
        System.setProperty("java.awt.headless", "true");
        System.setProperty("java.io.tmpdir", "/var/folders/bb/jflygsqs62q45k_4jdyk7knm0000gn/T/");
        System.setProperty("user.country", "CN");
        System.setProperty("user.dir", "/Users/skylove/CSE1105/repository-template/server/src/main");
        System.setProperty("user.home", "/Users/skylove");
        System.setProperty("user.language", "zh");
        System.setProperty("user.name", "skylove");
        System.setProperty("user.timezone", "Europe/Amsterdam");
    }

    private static void initializeClasses() {
        org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ReservationResponse_ESTest_scaffolding.class.getClassLoader(),
                "org.hibernate.annotations.OnDelete",
                "com.fasterxml.jackson.annotation.JsonProperty",
                "nl.tudelft.oopp.group43.project.models.Reservation",
                "nl.tudelft.oopp.group43.project.models.FoodOrder",
                "nl.tudelft.oopp.group43.project.payload.ReservationResponse",
                "nl.tudelft.oopp.group43.project.models.Building",
                "org.hibernate.annotations.OnDeleteAction",
                "com.fasterxml.jackson.annotation.JsonManagedReference",
                "nl.tudelft.oopp.group43.project.models.User",
                "com.fasterxml.jackson.annotation.JsonProperty$Access",
                "nl.tudelft.oopp.group43.project.models.Room",
                "com.fasterxml.jackson.annotation.JacksonAnnotation"
        );
    }

    private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException {
        mock(Class.forName("nl.tudelft.oopp.group43.project.models.Reservation", false, ReservationResponse_ESTest_scaffolding.class.getClassLoader()));
        mock(Class.forName("nl.tudelft.oopp.group43.project.models.Room", false, ReservationResponse_ESTest_scaffolding.class.getClassLoader()));
    }

    private static void resetClasses() {
        org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ReservationResponse_ESTest_scaffolding.class.getClassLoader());

        org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
                "nl.tudelft.oopp.group43.project.payload.ReservationResponse",
                "com.fasterxml.jackson.annotation.JsonProperty$Access",
                "nl.tudelft.oopp.group43.project.models.Reservation",
                "org.hibernate.annotations.OnDeleteAction",
                "nl.tudelft.oopp.group43.project.models.Room"
        );
    }
}
