/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 22:56:28 GMT 2020
 */

package nl.tudelft.oopp.group43.project.models;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import java.util.Set;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class RoleTest extends RoleTestScaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        Role role0 = new Role("nl.tudelft.oopp.group43.project.models.User", (Set) null);
        Set<User> set0 = role0.getUsers();
        assertNull(set0);
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        Role role0 = new Role();
        role0.setName("");
        String string0 = role0.getName();
        assertEquals("", string0);
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        Role role0 = new Role();
        Long long0 = new Long(0L);
        role0.setId(long0);
        Long long1 = role0.getId();
        assertEquals(0L, (long) long1);
    }

    @Test(timeout = 4000)
    public void test3() throws Throwable {
        Role role0 = new Role();
        Long long0 = new Long((-1L));
        role0.setId(long0);
        Long long1 = role0.getId();
        assertEquals((-1L), (long) long1);
    }

    @Test(timeout = 4000)
    public void test4() throws Throwable {
        Role role0 = new Role();
        Long long0 = new Long(1L);
        role0.setId(long0);
        Long long1 = role0.getId();
        assertEquals(1L, (long) long1);
    }

    @Test(timeout = 4000)
    public void test5() throws Throwable {
        Role role0 = new Role();
        Long long0 = role0.getId();
        assertNull(long0);
    }

    @Test(timeout = 4000)
    public void test6() throws Throwable {
        Role role0 = new Role();
        Set<User> set0 = role0.getUsers();
        role0.setUsers(set0);
        assertNull(role0.getId());
    }

    @Test(timeout = 4000)
    public void test7() throws Throwable {
        Role role0 = new Role();
        String string0 = role0.getName();
        assertNull(string0);
    }

    @Test(timeout = 4000)
    public void test8() throws Throwable {
        Role role0 = new Role();
        role0.setName("!}4[Yv");
        String string0 = role0.getName();
        assertEquals("!}4[Yv", string0);
    }
}
