/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 23:13:10 GMT 2020
 */

package nl.tudelft.oopp.group43.project.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import nl.tudelft.oopp.group43.project.service.EmailServiceImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;
import org.springframework.mail.javamail.JavaMailSender;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EmailServiceImpl_ESTest extends EmailServiceImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EmailServiceImpl emailServiceImpl0 = new EmailServiceImpl();
      JavaMailSender javaMailSender0 = mock(JavaMailSender.class, new ViolatedAssumptionAnswer());
      Injector.inject(emailServiceImpl0, (Class<?>) EmailServiceImpl.class, "javaMailSender", (Object) javaMailSender0);
      Injector.validateBean(emailServiceImpl0, (Class<?>) EmailServiceImpl.class);
      emailServiceImpl0.sendEmail("FRgeR}|DqDLqdMz ?cl");
  }
}
