/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun Mar 22 23:14:07 GMT 2020
 */

package nl.tudelft.oopp.group43.project.service;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class SecurityServiceImpl_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "nl.tudelft.oopp.group43.project.service.SecurityServiceImpl"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/bb/jflygsqs62q45k_4jdyk7knm0000gn/T/"); 
    java.lang.System.setProperty("user.country", "CN"); 
    java.lang.System.setProperty("user.dir", "/Users/skylove/CSE1105/repository-template/server/src/main"); 
    java.lang.System.setProperty("user.home", "/Users/skylove"); 
    java.lang.System.setProperty("user.language", "zh"); 
    java.lang.System.setProperty("user.name", "skylove"); 
    java.lang.System.setProperty("user.timezone", "Europe/Amsterdam"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(SecurityServiceImpl_ESTest_scaffolding.class.getClassLoader() ,
      "org.springframework.util.ReflectionUtils$FieldFilter",
      "com.fasterxml.jackson.annotation.JsonProperty",
      "nl.tudelft.oopp.group43.project.models.Role",
      "nl.tudelft.oopp.group43.project.service.SecurityService",
      "org.springframework.security.core.userdetails.UsernameNotFoundException",
      "org.springframework.util.ConcurrentReferenceHashMap$Reference",
      "org.springframework.util.ReflectionUtils$FieldCallback",
      "org.springframework.security.core.userdetails.UserDetailsService",
      "org.springframework.beans.factory.annotation.Autowired",
      "org.springframework.security.core.userdetails.User",
      "org.springframework.util.ConcurrentReferenceHashMap$Segment",
      "com.fasterxml.jackson.annotation.JacksonAnnotation",
      "org.springframework.data.domain.Sort$Direction",
      "nl.tudelft.oopp.group43.project.repositories.UserRepository",
      "org.springframework.security.core.context.ThreadLocalSecurityContextHolderStrategy",
      "org.springframework.data.repository.Repository",
      "org.springframework.security.core.AuthenticationException",
      "org.springframework.data.domain.Sort",
      "org.springframework.data.domain.Pageable",
      "org.springframework.security.core.context.SecurityContextHolder",
      "org.springframework.stereotype.Repository",
      "org.springframework.util.ConcurrentReferenceHashMap$WeakEntryReference",
      "nl.tudelft.oopp.group43.project.models.BikeReservation",
      "org.springframework.data.repository.PagingAndSortingRepository",
      "com.fasterxml.jackson.annotation.JsonCreator$Mode",
      "org.springframework.security.core.userdetails.User$UserBuilder",
      "org.springframework.util.ConcurrentReferenceHashMap$EntryIterator",
      "nl.tudelft.oopp.group43.project.models.User",
      "org.springframework.data.domain.Page",
      "org.springframework.data.domain.Example",
      "org.springframework.data.domain.Slice",
      "org.springframework.security.core.GrantedAuthority",
      "org.springframework.data.domain.Sort$NullHandling",
      "nl.tudelft.oopp.group43.project.models.FoodOrder",
      "org.springframework.security.core.context.SecurityContext",
      "org.springframework.data.util.Streamable",
      "org.springframework.security.authentication.AbstractAuthenticationToken",
      "nl.tudelft.oopp.group43.project.models.Building",
      "org.springframework.security.authentication.UsernamePasswordAuthenticationToken",
      "org.springframework.security.core.Authentication",
      "org.springframework.util.ConcurrentReferenceHashMap$Restructure",
      "org.springframework.util.ConcurrentReferenceHashMap$Task",
      "nl.tudelft.oopp.group43.project.models.Bike",
      "org.springframework.data.jpa.repository.JpaRepository",
      "org.springframework.util.ConcurrentReferenceHashMap$SoftEntryReference",
      "org.springframework.util.ConcurrentReferenceHashMap$EntrySet",
      "org.springframework.util.ConcurrentReferenceHashMap$Entry",
      "nl.tudelft.oopp.group43.project.service.SecurityServiceImpl",
      "org.springframework.util.ConcurrentReferenceHashMap$TaskOption",
      "org.springframework.data.repository.CrudRepository",
      "org.springframework.data.repository.NoRepositoryBean",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceManager",
      "org.springframework.util.ReflectionUtils$MethodCallback",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceType",
      "org.springframework.util.ConcurrentReferenceHashMap",
      "org.springframework.security.core.CredentialsContainer",
      "org.springframework.stereotype.Service",
      "org.springframework.beans.factory.annotation.Qualifier",
      "com.fasterxml.jackson.annotation.JsonIgnore",
      "org.springframework.security.core.userdetails.UserDetails",
      "org.springframework.security.core.context.InheritableThreadLocalSecurityContextHolderStrategy",
      "org.springframework.stereotype.Indexed",
      "com.fasterxml.jackson.annotation.JsonProperty$Access",
      "org.springframework.security.core.context.SecurityContextHolderStrategy",
      "org.springframework.util.ConcurrentReferenceHashMap$1",
      "org.springframework.util.ConcurrentReferenceHashMap$2",
      "org.springframework.util.ConcurrentReferenceHashMap$3",
      "org.springframework.util.ConcurrentReferenceHashMap$4",
      "org.springframework.security.authentication.AuthenticationManager",
      "org.springframework.security.core.context.SecurityContextImpl",
      "org.springframework.util.ConcurrentReferenceHashMap$Entries",
      "org.springframework.data.domain.ExampleMatcher",
      "org.springframework.data.domain.Sort$Order",
      "org.springframework.data.repository.query.QueryByExampleExecutor",
      "org.springframework.stereotype.Component",
      "nl.tudelft.oopp.group43.project.models.Reservation",
      "org.springframework.util.ReflectionUtils$MethodFilter",
      "org.springframework.util.ReflectionUtils",
      "com.fasterxml.jackson.annotation.JsonCreator",
      "org.springframework.data.domain.Sort$TypedSort",
      "org.springframework.util.ConcurrentReferenceHashMap$5",
      "org.springframework.security.core.authority.AuthorityUtils",
      "org.springframework.util.StringUtils",
      "org.springframework.util.Assert"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("nl.tudelft.oopp.group43.project.models.User", false, SecurityServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("nl.tudelft.oopp.group43.project.repositories.UserRepository", false, SecurityServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.springframework.security.authentication.AuthenticationManager", false, SecurityServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.springframework.security.core.Authentication", false, SecurityServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.springframework.security.core.userdetails.UserDetails", false, SecurityServiceImpl_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.springframework.security.core.userdetails.UserDetailsService", false, SecurityServiceImpl_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(SecurityServiceImpl_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "nl.tudelft.oopp.group43.project.service.SecurityServiceImpl",
      "org.springframework.util.StringUtils",
      "org.springframework.security.core.context.ThreadLocalSecurityContextHolderStrategy",
      "org.springframework.security.core.context.SecurityContextHolder",
      "org.springframework.security.authentication.AbstractAuthenticationToken",
      "org.springframework.security.authentication.UsernamePasswordAuthenticationToken",
      "org.springframework.security.core.context.SecurityContextImpl",
      "com.fasterxml.jackson.annotation.JsonProperty$Access",
      "com.fasterxml.jackson.annotation.JsonCreator$Mode",
      "nl.tudelft.oopp.group43.project.models.User",
      "org.springframework.security.core.authority.AuthorityUtils",
      "org.springframework.security.core.userdetails.User",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceType",
      "org.springframework.util.ConcurrentReferenceHashMap",
      "org.springframework.util.Assert",
      "org.springframework.util.ConcurrentReferenceHashMap$Segment",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceManager",
      "org.springframework.util.ReflectionUtils",
      "nl.tudelft.oopp.group43.project.models.Reservation",
      "org.springframework.data.domain.Sort$Direction",
      "org.springframework.data.domain.Sort",
      "org.springframework.util.ConcurrentReferenceHashMap$Task",
      "org.springframework.util.ConcurrentReferenceHashMap$5",
      "org.springframework.security.core.context.InheritableThreadLocalSecurityContextHolderStrategy",
      "org.springframework.data.domain.Sort$NullHandling",
      "org.springframework.data.domain.Sort$Order"
    );
  }
}
