/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 21:50:47 GMT 2020
 */

package nl.tudelft.oopp.group43.project.config;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import javax.persistence.EntityManagerFactory;
import nl.tudelft.oopp.group43.project.config.MainConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.springframework.mail.javamail.JavaMailSenderImpl;
import org.springframework.orm.jpa.JpaTransactionManager;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MainConfig_ESTest extends MainConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MainConfig mainConfig0 = new MainConfig();
      JavaMailSenderImpl javaMailSenderImpl0 = (JavaMailSenderImpl)mainConfig0.getJavaMailSender();
      assertEquals(587, javaMailSenderImpl0.getPort());
      assertEquals("smtp.office365.com", javaMailSenderImpl0.getHost());
      assertEquals("CSE1105Group43!", javaMailSenderImpl0.getPassword());
      assertEquals("Group43OOPP@hotmail.com", javaMailSenderImpl0.getUsername());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MainConfig mainConfig0 = new MainConfig();
      EntityManagerFactory entityManagerFactory0 = mock(EntityManagerFactory.class, new ViolatedAssumptionAnswer());
      JpaTransactionManager jpaTransactionManager0 = (JpaTransactionManager)mainConfig0.transactionManager(entityManagerFactory0);
      assertFalse(jpaTransactionManager0.isValidateExistingTransaction());
  }
}
